project_id = "fcyoaszptulrisdaifya"

[functions.chat]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.process-payment]
verify_jwt = true
